auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: TamChen
url: http://tamchen.github.io
feed: /atom.xml
author_info: <a href="http://tamchen.github.io/">TamChen</a>
